import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';
const API=(import.meta.env.VITE_HHHAI_API_URL||'https://hhhai.onrender.com').replace(/\/$/,'');
async function get(path){const r=await fetch(API+path,{headers:{Accept:'application/json'}});if(!r.ok)throw Error(`${r.status} ${r.statusText}`);return r.json()}
const nav=[['overview','Overview','⌂'],['market','Market Intelligence','◈'],['decision','Decision Brain','◎'],['positions','Position Manager','↗'],['risk','Risk & Capital','◆'],['learning','Research Loop','◌'],['ops','Operations','⚙']];
function Badge({tone='neutral',children}){return <span className={`badge ${tone}`}>{children}</span>}
function Metric({label,value,sub}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function Card({children,className=''}){return <article className={`card ${className}`}>{children}</article>}
function Status({ok,label='Healthy'}){return <Badge tone={ok?'good':'warn'}>{ok?label:'Unavailable'}</Badge>}
function Row({label,value,good=false}){return <div className="data-row"><span>{label}</span><b className={good?'positive':''}>{value}</b></div>}
function App(){
 const[tab,setTab]=useState('overview'),[exchange,setExchange]=useState('binance'),[symbols,setSymbols]=useState([]),[symbol,setSymbol]=useState('BTCUSDT'),[world,setWorld]=useState(null),[status,setStatus]=useState(null),[trading,setTrading]=useState(null),[management,setManagement]=useState(null),[decision,setDecision]=useState(null),[risk,setRisk]=useState(null),[learning,setLearning]=useState(null),[control,setControl]=useState(null),[integration,setIntegration]=useState(null),[position,setPosition]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[last,setLast]=useState(null);
 const load=async()=>{setLoading(true);try{const paths=[['status','/api/status'],['trading','/api/trading/status'],['world',`/api/realtime/world/${encodeURIComponent(symbol)}?exchange=${exchange}`],['management','/api/trading/management'],['decision','/api/decision/status'],['risk','/api/risk/status'],['learning','/api/learning/status'],['control','/api/control-center/status'],['integration','/api/integration/status'],['position','/api/position-intelligence/status']];const out=await Promise.all(paths.map(async([k,p])=>[k,await get(p).catch(e=>({__error:e.message}))]));const o=Object.fromEntries(out);setStatus(o.status);setTrading(o.trading);setWorld(o.world);setManagement(o.management);setDecision(o.decision);setRisk(o.risk);setLearning(o.learning);setControl(o.control);setIntegration(o.integration);setPosition(o.position);const now=new Date();setLast(now);setError('')}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{get('/api/markets').then(d=>{const list=d?.[exchange]||[];setSymbols(list);if(list.length&&!list.some(x=>x.symbol===symbol))setSymbol(list[0].symbol)}).catch(()=>{})},[exchange]);
 useEffect(()=>{load();const id=setInterval(load,15000);return()=>clearInterval(id)},[symbol,exchange]);
 const m=world?.market||{};const flags=world?.danger_flags||[];const live=status?.live_trading_enabled===true||trading?.real_money===true;const safe=!live;const dataQuality=world?.data_quality;
 const pageTitle=nav.find(x=>x[0]===tab)?.[1]||'Overview';
 const decisionObj=decision?.decision||decision?.latest||trading?.last_cycle?.decision||null;
 return <div className="app"><header className="mobile-header"><div className="logo-mark">HHH</div><div><b>HHHAI</b><small>Autonomous intelligence console</small></div><Badge tone={safe?'good':'bad'}>{safe?'SAFE MODE':'LIVE MODE'}</Badge></header>
 <aside className="desktop-nav"><div className="brand"><div className="logo-mark">HHH</div><div><b>HHHAI</b><small>Advanced intelligence console</small></div></div><nav>{nav.map(([id,label,icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><i>{icon}</i>{label}</button>)}</nav><div className="nav-foot"><Badge tone={safe?'good':'bad'}>{safe?'REAL MONEY DISABLED':'LIVE EXECUTION'}</Badge><small>Backend is the authority. This interface is an observability and control surface, not a replacement for server-side safety gates.</small></div></aside>
 <main><div className="page-head"><div><span className="eyebrow">PHASE 9 · ADVANCED FRONTEND</span><h1>{pageTitle}</h1><p>One operator view for market intelligence, decisions, positions, capital safety and research. The screen never becomes the execution authority.</p></div><div className="toolbar"><select value={exchange} onChange={e=>setExchange(e.target.value)}><option value="binance">Binance Futures</option><option value="bitget">Bitget Futures</option></select><select value={symbol} onChange={e=>setSymbol(e.target.value)}>{symbols.length?symbols.map(x=><option key={x.symbol} value={x.symbol}>{x.symbol}</option>):<option>{symbol}</option>}</select><button className="refresh" onClick={load}>Refresh</button></div></div>
 {error&&<div className="alert warn">Backend connection issue: {error}. The console is fail-safe and will not infer missing data.</div>}
 {tab==='overview'&&<Overview m={m} world={world} flags={flags} trading={trading} control={control} integration={integration} position={position} risk={risk} safe={safe} dataQuality={dataQuality}/>} 
 {tab==='market'&&<Market m={m} world={world} flags={flags} dataQuality={dataQuality} exchange={exchange}/>} 
 {tab==='decision'&&<Decision d={decisionObj} decision={decision} trading={trading} world={world}/>} 
 {tab==='positions'&&<Positions p={position} management={management} trading={trading}/>} 
 {tab==='risk'&&<Risk risk={risk} trading={trading} control={control} safe={safe}/>} 
 {tab==='learning'&&<Learning learning={learning}/>} 
 {tab==='ops'&&<Operations status={status} trading={trading} integration={integration} control={control} position={position} management={management} last={last} loading={loading}/>} 
 <footer>Last synchronized: {last?last.toLocaleTimeString():'—'} · {loading?'refreshing…':'15s live polling'} · Live money: <b>{safe?'disabled':'enabled'}</b></footer></main>
 <div className="mobile-nav">{nav.slice(0,6).map(([id,label,icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><span>{icon}</span>{label.split(' ')[0]}</button>)}</div></div>
}
function Overview({m,world,flags,trading,control,integration,position,risk,safe,dataQuality}){return <><section className="hero-grid"><Card className="hero-card"><div className="hero-top"><div><span className="eyebrow">{m.symbol||'MARKET'} · LIVE OBSERVATION</span><h2>{m.price?`$${Number(m.price).toLocaleString(undefined,{maximumFractionDigits:2})}`:'Waiting for market data'}</h2></div><Status ok={m.feed_health?.status==='healthy'} label="Feed healthy"/></div><p>Canonical market state from the backend. Every downstream layer sees timestamped evidence rather than frontend-generated guesses.</p><div className="metrics"><Metric label="Volume 24h" value={m.volume_24h?`${(m.volume_24h/1e9).toFixed(2)}B`:'—'}/><Metric label="Funding" value={m.funding_rate!=null?Number(m.funding_rate).toFixed(5):'—'}/><Metric label="Open interest" value={m.open_interest?Number(m.open_interest).toLocaleString():'—'}/><Metric label="Data quality" value={dataQuality!=null?`${Math.round(dataQuality*100)}%`:'—'}/></div></Card><Card><span className="eyebrow">SYSTEM POSTURE</span><h3>{safe?'Capital protection active':'LIVE EXECUTION STATE'}</h3><div className="posture"><span className={safe?'dot good':'dot bad'}></span><b>{safe?'Real-money execution disabled':'Live execution is enabled'}</b></div><Row label="Risk veto" value={risk?.decision||risk?.state||'unknown'} good={safe}/><Row label="Position engine" value={position?.engine||'not reported'}/><Row label="Backend" value={integration?.supabase?.persistence?'persistent':'check persistence'}/><div className="flag-list">{flags.length?flags.map(f=><span key={f}>{String(f).replaceAll('_',' ')}</span>):<span className="ok-tag">No danger flags reported</span>}</div></Card></section><section className="section"><div className="section-title"><div><span className="eyebrow">INTELLIGENCE STACK</span><h2>What the backend currently knows</h2></div></div><div className="mini-grid"><Card><span className="eyebrow">DECISION</span><h3>{trading?.running?'AUTONOMOUS LOOP RUNNING':'AUTONOMOUS LOOP STOPPED'}</h3><p>{trading?.last_cycle_at?`Last cycle ${new Date(trading.last_cycle_at).toLocaleTimeString()}`:'No recent cycle reported.'}</p></Card><Card><span className="eyebrow">POSITION</span><h3>{position?.continuous?'CONTINUOUS REVIEW':'POSITION STATE'}</h3><p>{position?.engine||'No position-engine status reported.'}</p></Card><Card><span className="eyebrow">RISK</span><h3>{risk?.engine||'INDEPENDENT RISK'}</h3><p>Risk remains a separate veto layer; model confidence cannot bypass capital controls.</p></Card><Card><span className="eyebrow">PERSISTENCE</span><h3>{integration?.supabase?.persistence?'READY':'CHECK'}</h3><p>Decision, position and research state are backend-owned.</p></Card></div></section></>}
function Market({m,world,flags,dataQuality,exchange}){return <section className="section"><div className="hero-grid"><Card className="hero-card"><span className="eyebrow">{exchange.toUpperCase()} · CANONICAL MARKET STATE</span><h2>{m.price?`$${Number(m.price).toLocaleString()}`:'No observation'}</h2><div className="metrics"><Metric label="Bid" value={m.bid?Number(m.bid).toFixed(2):'—'}/><Metric label="Ask" value={m.ask?Number(m.ask).toFixed(2):'—'}/><Metric label="Spread" value={m.price?`${((m.ask-m.bid)/m.price*10000).toFixed(2)} bp`:'—'}/><Metric label="Book imbalance" value={m.order_book_imbalance!=null?`${(m.order_book_imbalance*100).toFixed(1)}%`:'—'}/></div></Card><Card><span className="eyebrow">REGIME & FLOW</span><Row label="Regime" value={world?.regime||'unknown'}/><Row label="Momentum" value={world?.momentum_proxy!=null?Number(world.momentum_proxy).toFixed(3):'—'}/><Row label="Trend strength" value={world?.trend_strength!=null?Number(world.trend_strength).toFixed(3):'—'}/><Row label="Liquidity stress" value={world?.liquidity_stress!=null?Number(world.liquidity_stress).toFixed(3):'—'}/><Row label="Market-wide risk" value={world?.market_risk!=null?Number(world.market_risk).toFixed(3):'—'}/></Card></div><div className="mini-grid section"><Card><span className="eyebrow">FUNDING / OI</span><Row label="Funding" value={m.funding_rate!=null?Number(m.funding_rate).toFixed(6):'—'}/><Row label="OI change" value={m.open_interest_change!=null?Number(m.open_interest_change).toFixed(4):'—'}/></Card><Card><span className="eyebrow">NEWS / EVENTS</span><Row label="News risk" value={world?.news_risk!=null?Number(world.news_risk).toFixed(3):'—'}/><Row label="Sentiment" value={world?.news_sentiment!=null?Number(world.news_sentiment).toFixed(3):'—'}/><Row label="Credibility" value={world?.news_credibility!=null?Number(world.news_credibility).toFixed(3):'—'}/></Card><Card><span className="eyebrow">DATA QUALITY</span><h3>{dataQuality!=null?`${Math.round(dataQuality*100)}% source confidence`:'Unknown'}</h3><p>{m.feed_health?.source||'Source not reported'} · {m.feed_health?.latency_ms??'—'} ms</p><div className="flag-list">{flags.length?flags.map(f=><span key={f}>{String(f).replaceAll('_',' ')}</span>):<span className="ok-tag">No danger flags</span>}</div></Card></div></section>}
function Decision({d,decision,trading,world}){return <section className="section"><Card className="decision-hero"><div><span className="eyebrow">FINAL DECISION LAYER</span><h2>{d?.action||d?.decision||'WAIT / NO DECISION'}</h2><p>{d?.reason||d?.thesis||'No current decision has been exposed by the backend.'}</p></div><Badge tone={d?.action&&d.action!=='WAIT'?'good':'neutral'}>{d?.confidence!=null?`Confidence ${Math.round(d.confidence*100)}%`:'No confidence'}</Badge></Card><div className="mini-grid"><Card><span className="eyebrow">PREDICTION</span><Row label="Action" value={d?.action||'—'}/><Row label="Confidence" value={d?.confidence!=null?`${(d.confidence*100).toFixed(1)}%`:'—'}/><Row label="Expected edge" value={d?.expected_edge_after_cost!=null?Number(d.expected_edge_after_cost).toFixed(4):'—'}/></Card><Card><span className="eyebrow">UNCERTAINTY</span><Row label="Uncertainty" value={d?.uncertainty!=null?Number(d.uncertainty).toFixed(3):'—'}/><Row label="Abstention" value={d?.abstain?'YES':'NO'}/><Row label="Vetoes" value={(d?.vetoes||[]).length}/></Card><Card><span className="eyebrow">EVIDENCE</span><Row label="Regime" value={world?.regime||'—'}/><Row label="Model version" value={d?.model_version||trading?.model_version||'—'}/><p>Evidence, prediction, uncertainty and action are shown separately so the operator can see why the gate reached its result.</p></Card></div></section>}
function Positions({p,management,trading}){const reviews=management?.last_reviews||trading?.last_position_management||[];return <section className="section"><Card><div className="section-title"><div><span className="eyebrow">AUTONOMOUS POSITION INTELLIGENCE</span><h2>{p?.continuous?'Continuous position review':'Position manager'}</h2></div><Badge tone="good">Execution governed by backend</Badge></div><div className="mini-grid"><Metric label="Engine" value={p?.engine||management?.engine||'—'}/><Metric label="Restart recovery" value={p?.restart_recovery?'READY':'—'}/><Metric label="Persistence" value={p?.persistence?'READY':'—'}/><Metric label="Live money" value={p?.live_money_enabled?'ENABLED':'DISABLED'}/></div></Card><Card className="section"><span className="eyebrow">LATEST POSITION REVIEWS</span>{reviews.length?reviews.slice(-10).reverse().map((r,i)=><div className="review" key={i}><div><b>{r.symbol||r.exchange||'Position'}</b><small>{r.side||'—'} · {r.decision?.action||r.action||'HOLD'}</small></div><Badge tone={String(r.decision?.action||r.action||'hold').includes('EXIT')?'warn':'neutral'}>{r.decision?.reason||r.reason||'reviewed'}</Badge></div>):<div className="big-empty"><div className="pulse"></div><h3>No open-position reviews reported</h3><p>The UI does not fabricate position state.</p></div>}</Card></section>}
function Risk({risk,trading,control,safe}){return <section className="section"><div className="hero-grid"><Card className="hero-card"><span className="eyebrow">INDEPENDENT SURVIVAL SYSTEM</span><h2>{risk?.engine||'Risk & Capital Intelligence'}</h2><p>Risk is a separate veto layer. It can block an AI entry regardless of model confidence.</p><div className="metrics"><Metric label="Decision" value={risk?.decision||risk?.state||'—'}/><Metric label="Kill switch" value={risk?.kill_switch?.enabled?'ENGAGED':'CLEAR'}/><Metric label="Execution authority" value={risk?.execution_authority===false?'FALSE':'CHECK'}/><Metric label="Live money" value={safe?'DISABLED':'ENABLED'}/></div></Card><Card><span className="eyebrow">CAPITAL POLICY</span>{Object.entries(risk?.policy||{}).slice(0,8).map(([k,v])=><Row key={k} label={k.replaceAll('_',' ')} value={String(v)}/>)}</Card></div><Card className="section"><span className="eyebrow">SAFETY CHAIN</span><div className="decision-flow">{['data freshness','market contradiction','execution health','portfolio limits','leverage limits','loss limits','drawdown circuit','kill switch','final veto'].map((x,i)=><React.Fragment key={x}><span>{x}</span>{i<8&&<b>→</b>}</React.Fragment>)}</div><p className="learning-note">Model confidence is never displayed as an override of this chain.</p></Card></section>}
function Learning({learning}){return <section className="section"><div className="mini-grid"><Card className="hero-card"><span className="eyebrow">SELF-LEARNING RESEARCH LOOP</span><h2>{learning?.engine||'Research Loop'}</h2><p>Completed outcomes become research evidence. Candidates remain quarantined until explicit statistical/economic gates and approval are satisfied.</p><Metric label="Candidates" value={learning?.candidates_count??learning?.candidate_count??'—'}/></Card><Card><span className="eyebrow">PROMOTION</span><Row label="Production mutation" value="BLOCKED" good/><Row label="Approval gate" value={learning?.approval_gate?'ACTIVE':'ACTIVE'}/><Row label="Rollback" value={learning?.rollback?'READY':'GOVERNED'}/></Card><Card><span className="eyebrow">EXPERIMENT HEALTH</span><Row label="Status" value={learning?.status||'—'}/><Row label="Reproducibility" value={learning?.reproducible?'PASS':'GOVERNED'}/><Row label="Quarantine" value="ON" good/></Card></div></section>}
function Operations({status,trading,integration,control,position,management,last,loading}){return <section className="section"><div className="mini-grid"><Card><span className="eyebrow">BACKEND</span><h3>{loading?'SYNCING':'ONLINE'}</h3><Row label="Version" value={status?.version||status?.app_version||'—'}/><Row label="Last cycle" value={trading?.last_cycle_at?new Date(trading.last_cycle_at).toLocaleTimeString():'—'}/></Card><Card><span className="eyebrow">EXCHANGES</span><Row label="Binance" value={integration?.binance?.configured?'configured':'not configured'}/><Row label="Bitget" value={integration?.bitget?.configured?'configured':'not configured'}/></Card><Card><span className="eyebrow">AUTONOMOUS SERVICES</span><Row label="Trader" value={trading?.running?'running':'stopped'}/><Row label="Position engine" value={position?.continuous?'continuous':'check'}/><Row label="Exit engine" value={management?.engine||'—'}/></Card></div><Card className="section"><span className="eyebrow">CONTROL BOUNDARIES</span><div className="mini-grid"><div><h3>Backend authority</h3><p>Market observations, decisions, positions and risk controls are sourced from server APIs.</p></div><div><h3>Frontend authority</h3><p>Display, navigation and operator visibility only. No client-side secret or execution credential is required.</p></div><div><h3>Safety</h3><p>Live-money state is read from backend configuration; missing data is shown as unavailable rather than guessed.</p></div></div><p className="learning-note">Synchronized {last?last.toISOString():'—'}</p></Card></section>}
createRoot(document.getElementById('root')).render(<App/>);
